# Generated by Django 2.1.2 on 2018-11-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellog', '0002_auto_20181114_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
